package rfl.astroimagej.dev.queries;

import java.util.ArrayList;
import java.util.List;

public class QueryResult {

	// object data
	private String objectId = null;
	
	// Simbad query 
	private String simbadId = null;
	private Double simbadRaHr = null;
	private Double simbadDecDeg = null;
	private Double magB = null;
	private Double magV = null;
	private Double magR = null;
	private Double magI = null;
	
	// Vsp query
	private List<FieldObject> fieldObjects = null;

	public QueryResult(String objectId) {
		this.objectId = objectId;
		
		this.simbadId = "WASP-12";
		this.simbadRaHr = 6.50911;
		this.simbadDecDeg = 29.67230;
		magB = 12.14;
		magV = 11.57;
		magR = null;
		magI = null;
		
		this.fieldObjects = new ArrayList<>();
	}
	
	// ** List<FieldObject> customer getter / setters
	public List<FieldObject> getFieldObjects() {
		return fieldObjects;
	}

	public void setFieldObject(FieldObject fieldObject) {
		fieldObjects.add(fieldObject);
	}	
	
	// read-only objectId
	public String getObjectId() {
		return objectId;
	}
	
	
	// ***************************** autogenerated

	public String getSimbadId() {
		return simbadId;
	}

	public void setSimbadId(String simbadId) {
		this.simbadId = simbadId;
	}

	public Double getSimbadRaHr() {
		return simbadRaHr;
	}

	public void setSimbadRaHr(Double simbadRaHr) {
		this.simbadRaHr = simbadRaHr;
	}

	public Double getSimbadDecDeg() {
		return simbadDecDeg;
	}

	public void setSimbadDecDeg(Double simbadDecDeg) {
		this.simbadDecDeg = simbadDecDeg;
	}

	public Double getMagB() {
		return magB;
	}

	public void setMagB(Double magB) {
		this.magB = magB;
	}

	public Double getMagV() {
		return magV;
	}

	public void setMagV(Double magV) {
		this.magV = magV;
	}

	public Double getMagR() {
		return magR;
	}

	public void setMagR(Double magR) {
		this.magR = magR;
	}

	public Double getMagI() {
		return magI;
	}

	public void setMagI(Double magI) {
		this.magI = magI;
	}

	@Override
	public String toString() {
		return "QueryResult [objectId=" + objectId + ", simbadId=" + simbadId + ", simbadRaHr=" + simbadRaHr
				+ ", simbadDecDeg=" + simbadDecDeg + ", magB=" + magB + ", magV=" + magV + ", magR=" + magR + ", magI="
				+ magI + ", fieldObjects=" + fieldObjects + "]";
	}
	
}
